apiVersion: apps/v1
kind: Deployment
metadata:
  name: devshelf-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devshelf
  template:
    metadata:
      labels:
        app: devshelf
    spec:
      containers:
      - name: devshelf
        image: 500888951988.dkr.ecr.eu-north-1.amazonaws.com/devshelf-app:26022fada3b9ac54949ab3bb9de6201404e3c21e
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devshelf-service
  namespace: default
spec:
  selector:
    app: devshelf
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
